version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    ignore:
      # GitHub always delivers the latest versions for each major
      # release tag, so handle updates manually
      - dependency-name: "actions/*"
      - dependency-name: "github/codeql-action/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    ignore:
      - dependency-name: "@types/node"
        versions: ["15.x", "14.x", "13.x"]
      - dependency-name: "xdg-basedir"
        # 5.0.0 has breaking changes as they switch to named exports
        # and convert the module to ESM
        # We can't use it until we switch to ESM across the project
        # See release notes: https://github.com/sindresorhus/xdg-basedir/releases/tag/v5.0.0
        versions: ["5.x"]
